---
:concurrency: 5
:queues:
  - [default, 6]
  - [distribution, 6]
  - [push, 4]
  - [mailers, 2]
  - [pull]
  - [chewy]
  - [removal]
  - [reblog-removal]
  - [shared]
:scheduler:
  :listened_queues_only: true
:schedule:
  scheduled_statuses_scheduler:
    every: '5m'
    class: Scheduler::ScheduledStatusesScheduler
    queue: scheduler
  media_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::MediaCleanupScheduler
    queue: scheduler
  follow_recommendations_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(6..9) %> * * *'
    class: Scheduler::FollowRecommendationsScheduler
    queue: scheduler
  doorkeeper_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
    queue: scheduler
  user_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * *'
    class: Scheduler::UserCleanupScheduler
    queue: scheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::IpCleanupScheduler
    queue: scheduler
  backup_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::BackupCleanupScheduler
    queue: scheduler
  instance_refresh_scheduler:
    cron: '0 * * * *'
    class: Scheduler::InstanceRefreshScheduler
    queue: scheduler
  users_approval_scheduler:
    every: '5m'
    class: Scheduler::UsersApprovalScheduler
    queue: scheduler
  refresh_receipt_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::RefreshReceiptScheduler
    queue: scheduler
  tv_create_program_records_scheduler:
    every: '10m'
    class: Scheduler::TvCreateProgramRecordsScheduler
    queue: scheduler
  tv_refetch_channels_list_scheduler:
    cron: '0 1 * * *'
    class: Scheduler::TvRefetchChannelsListScheduler
    queue: scheduler
  device_verification_cleanup_scheduler:
    cron: '0 2 * * *'
    class: Scheduler::DeviceVerificationCleanupWorker
    queue: scheduler
