# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_updated.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("account_updated.proto", :syntax => :proto3) do
    add_message "AccountUpdated" do
      optional :account_id, :int64, 1
      optional :username, :string, 2
      optional :display_name, :string, 3
      optional :avatar_url, :string, 4
      optional :header_url, :string, 5
      optional :website, :string, 6
      optional :bio, :string, 7
      optional :location, :string, 8
      repeated :fields_changed, :enum, 9, "AccountUpdated.AccountFields"
    end
    add_enum "AccountUpdated.AccountFields" do
      value :DISPLAY_NAME, 0
      value :AVATAR_URL, 1
      value :HEADER_URL, 2
      value :WEBSITE, 3
      value :BIO, 4
      value :LOCATION, 5
    end
  end
end

AccountUpdated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountUpdated").msgclass
AccountUpdated::AccountFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountUpdated.AccountFields").enummodule
