# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report_created.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("report_created.proto", :syntax => :proto3) do
    add_message "ReportCreated" do
      optional :id, :int64, 1
      optional :account_id, :int64, 2
      optional :account_username, :string, 3
      optional :target_account_id, :int64, 4
      optional :target_account_username, :string, 5
      optional :comment, :string, 6
      repeated :status_ids, :int64, 7
      repeated :rule_ids, :int64, 8
      optional :status_id, :int64, 9
      optional :report_set_id, :string, 10
      repeated :image_ids, :int64, 11
      repeated :video_ids, :int64, 12
    end
  end
end

ReportCreated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReportCreated").msgclass
