# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status_created.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("status_created.proto", :syntax => :proto3) do
    add_message "StatusCreated" do
      optional :id, :int64, 1
      optional :account_id, :int64, 2
      optional :text, :string, 3
      repeated :media_attachments, :message, 4, "StatusCreated.MediaAttachment"
    end
    add_message "StatusCreated.MediaAttachment" do
      optional :id, :int64, 1
      optional :url, :string, 2
      optional :type, :string, 3
    end
  end
end

StatusCreated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StatusCreated").msgclass
StatusCreated::MediaAttachment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StatusCreated.MediaAttachment").msgclass
